dependencies:
  - ProjectOpenSea/seaport@1.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - 'seaport=ProjectOpenSea/seaport@1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
