// autogenerated by brownie
// do not modify the existing settings
module.exports = {
  networks: {
    hardhat: {
      chainId: 1,
      forking: {
        url: 'https://eth-mainnet.alchemyapi.io/v2/VFV539yhBGYpCjqcP5DHwYZ5IXd9KIl1',
      },
      hardfork: 'london',
      // base fee of 0 allows use of 0 gas price when testing
      initialBaseFeePerGas: 0,
      // brownie expects calls and transactions to throw on revert
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
    },
  },
};
